const majorsRaw=`matto|Il Matto|nuovo inizio, libertà, fiducia, salto nell'ignoto|imprudenza, esitazione, rischio non calcolato
mago|Il Mago|iniziativa, volontà, abilità, risorse|talento disperso, manipolazione, insicurezza
papessa|La Papessa|intuizione, silenzio, conoscenza interiore|intuizione ignorata, segreti, chiusura
imperatrice|L'Imperatrice|crescita, creatività, cura, abbondanza|blocco creativo, dipendenza, trascurarsi
imperatore|L'Imperatore|struttura, autorità, confini, stabilità|rigidità, controllo eccessivo, autoritarismo
papa|Il Papa|tradizione, insegnamento, valori, guida|conformismo, regole da rivedere, via non convenzionale
amanti|Gli Amanti|unione, scelta coerente, attrazione, valori|disallineamento, scelta evitata, conflitto di valori
carro|Il Carro|direzione, determinazione, disciplina, avanzamento|perdita di direzione, fretta, forze in conflitto
forza|La Forza|coraggio calmo, autocontrollo, pazienza|insicurezza, reattività, energia trattenuta
eremita|L'Eremita|ricerca interiore, prudenza, solitudine utile|isolamento, chiusura, fuga dal confronto
ruota|La Ruota della Fortuna|ciclo che cambia, svolta, opportunità|resistenza al cambiamento, ritardo, schema ripetuto
giustizia|La Giustizia|equilibrio, responsabilità, verità, conseguenze|parzialità, negazione, squilibrio
appeso|L'Appeso|pausa necessaria, nuova prospettiva, resa|stallo sterile, sacrificio inutile, resistenza
morte|La Morte|chiusura, trasformazione, rilascio, passaggio|attaccamento, paura di chiudere, transizione rallentata
temperanza|La Temperanza|integrazione, misura, guarigione, mediazione|eccessi, impazienza, squilibrio
diavolo|Il Diavolo|desiderio, attaccamento, dipendenza, impulsi|liberazione, presa di coscienza, autonomia
torre|La Torre|rottura, verità improvvisa, struttura che crolla|crisi evitata, paura del cambiamento, crollo rimandato
stella|La Stella|speranza, autenticità, fiducia, rigenerazione|sfiducia, scoraggiamento, speranza fragile
luna|La Luna|inconscio, ambiguità, sensibilità, nebbia|paure riconosciute, autoinganno che emerge
sole|Il Sole|chiarezza, vitalità, gioia, successo|gioia attenuata, aspettative alte, luce non vissuta
giudizio|Il Giudizio|risveglio, chiamata, revisione, decisione|autocritica, chiamata ignorata, passato non chiuso
mondo|Il Mondo|compimento, integrazione, risultato, chiusura|incompiutezza, ritardo, ultimo passaggio`;

const suitRaw={
Bastoni:`Asso|scintilla, iniziativa, entusiasmo|energia bloccata, partenza rimandata;Due|pianificazione, scelta, orizzonte|timore di esporsi, scelta rinviata;Tre|espansione, primi risultati, prospettiva|ritardi, aspettative deluse;Quattro|stabilità, celebrazione, casa|tensione nel gruppo, base fragile;Cinque|competizione, attrito, confronto|conflitto evitato, tensione interna;Sei|riconoscimento, vittoria, visibilità|bisogno di approvazione, successo fragile;Sette|difesa, fermezza, confini|stanchezza, sentirsi sopraffatti;Otto|velocità, notizie, movimento|ritardi, comunicazioni confuse;Nove|resilienza, prudenza, resistenza|esaurimento, difese troppo alte;Dieci|peso, responsabilità, carico|delegare, alleggerire il carico;Fante|curiosità, messaggio, esplorazione|idea acerba, impazienza;Cavaliere|azione, slancio, avventura|impulsività, irrequietezza;Regina|fiducia, calore, magnetismo|insicurezza, gelosia;Re|visione, leadership, impresa|arroganza, comando senza ascolto`,
Coppe:`Asso|apertura emotiva, amore, intuizione|emozioni trattenute, vulnerabilità negata;Due|reciprocità, incontro, accordo|squilibrio relazionale, distanza;Tre|amicizia, condivisione, festa|eccessi, dinamiche di gruppo confuse;Quattro|apatia, pausa emotiva, occasione non vista|ritorno dell'interesse, nuova apertura;Cinque|perdita, rimpianto, dolore|accettazione, recupero;Sei|nostalgia, memoria, gentilezza|idealizzazione del passato;Sette|possibilità, immaginazione, illusione|scelta che si chiarisce;Otto|distacco, lasciare ciò che non nutre|paura di andarsene, ritorno;Nove|soddisfazione, desiderio realizzato|gratificazione superficiale, eccesso;Dieci|armonia, famiglia, appartenenza|tensione domestica, disconnessione;Fante|sensibilità, messaggio affettivo, intuizione|immaturità emotiva, fantasia;Cavaliere|romanticismo, proposta, idealismo|idealizzazione, promesse vaghe;Regina|empatia, ascolto, profondità|confini emotivi deboli, insicurezza;Re|maturità emotiva, diplomazia, calma|freddezza, manipolazione affettiva`,
Spade:`Asso|chiarezza, verità, decisione|confusione, verità parziale;Due|stallo, scelta difficile, equilibrio precario|informazioni che emergono, scelta inevitabile;Tre|dolore, separazione, delusione|guarigione, rilascio del dolore;Quattro|riposo, recupero, pausa|irrequietezza, stanchezza ignorata;Cinque|conflitto, vittoria amara, tensione|rimorso, riconciliazione possibile;Sei|transizione, passaggio, recupero|bagaglio non lasciato, ritorno;Sette|strategia, discrezione, astuzia|verità scoperta, strategia che non regge;Otto|limitazione percepita, paura, vincolo mentale|liberazione, nuova prospettiva;Nove|ansia, preoccupazione, colpa|sollievo graduale, paura affrontata;Dieci|fine dolorosa, rottura, conclusione|ripresa dopo il fondo, fine rimandata;Fante|curiosità mentale, osservazione, notizia|pettegolezzo, informazione incompleta;Cavaliere|azione decisa, confronto diretto|aggressività, fretta;Regina|discernimento, indipendenza, confini chiari|durezza, cinismo, isolamento;Re|razionalità, strategia, autorità mentale|rigidità, uso freddo del potere`,
Denari:`Asso|opportunità concreta, risorsa, base stabile|occasione persa, ritardo materiale;Due|equilibrio pratico, adattamento, priorità|sovraccarico, disordine;Tre|competenza, collaborazione, mestiere|lavoro poco coordinato, capacità non valorizzata;Quattro|sicurezza, conservazione, controllo|paura della perdita, controllo eccessivo;Cinque|difficoltà, scarsità, bisogno di aiuto|recupero, sostegno disponibile;Sei|generosità, scambio, sostegno|aiuto condizionato, scambio squilibrato;Sette|pazienza, valutazione, investimento|impazienza, rendimento insufficiente;Otto|apprendimento, disciplina, miglioramento|perfezionismo, lavoro meccanico;Nove|autonomia, benessere, risultati|dipendenza materiale, spesa eccessiva;Dieci|stabilità duratura, famiglia, patrimonio|instabilità familiare o finanziaria;Fante|studio, opportunità, progetto|procrastinazione, piano poco pratico;Cavaliere|costanza, affidabilità, metodo|stagnazione, routine sterile;Regina|praticità, cura, gestione delle risorse|ansia materiale, trascurarsi;Re|solidità, gestione, successo concreto|materialismo, rigidità, avidità`
};

const element={Bastoni:"Fuoco",Coppe:"Acqua",Spade:"Aria",Denari:"Terra"};
const majors=majorsRaw.split("\n").map(r=>{const[id,name,upright,reversed]=r.split("|");return{id,name,arcana:"Maggiore",element:"Spirito",upright,reversed}});
const minors=Object.entries(suitRaw).flatMap(([suit,raw])=>raw.split(";").map(r=>{const[rank,upright,reversed]=r.split("|");return{id:suit.toLowerCase()+"-"+rank.toLowerCase(),name:rank+" di "+suit,arcana:"Minore",suit,rank,element:element[suit],upright,reversed}}));
const deck=[...majors,...minors];

const spreads={
one:{name:"Una carta",positions:[{label:"Messaggio",focus:"il nucleo della domanda"}]},
three:{name:"Tre carte",positions:[{label:"Passato",focus:"ciò che ha preparato la situazione"},{label:"Presente",focus:"la dinamica attiva adesso"},{label:"Futuro",focus:"la tendenza se il quadro resta questo"}]},
celtic:{name:"Croce Celtica",positions:[{label:"1. Presente",focus:"il cuore della situazione"},{label:"2. Sfida",focus:"la forza che incrocia o mette alla prova"},{label:"3. Radice",focus:"la base profonda o inconscia"},{label:"4. Passato",focus:"ciò che sta perdendo forza"},{label:"5. Possibile",focus:"ciò che può maturare o l'obiettivo cosciente"},{label:"6. Prossimo passo",focus:"la tendenza immediata"},{label:"7. Tu",focus:"atteggiamento e risorse personali"},{label:"8. Ambiente",focus:"influenze esterne e contesto"},{label:"9. Speranze e timori",focus:"desiderio e paura che convivono"},{label:"10. Esito potenziale",focus:"la direzione se le dinamiche restano invariate"}]}
};

let currentSpread="three",drawn=[],revealed=new Set();
const q=document.querySelector("#question"), reversals=document.querySelector("#reversals"), drawBtn=document.querySelector("#drawBtn"), deckStage=document.querySelector("#deckStage"), spreadArea=document.querySelector("#spreadArea"), revealNote=document.querySelector("#revealNote"), result=document.querySelector("#result"), oracleText=document.querySelector("#oracleText");

document.querySelectorAll('input[name="spread"]').forEach(r=>r.addEventListener("change",e=>{currentSpread=e.target.value;document.querySelectorAll(".spread-option").forEach(x=>x.classList.toggle("active",x.dataset.spreadLabel===currentSpread));resetTable(false)}));
drawBtn.addEventListener("click",draw);
function rnd(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function draw(){const pool=shuffle([...deck]);drawn=spreads[currentSpread].positions.map((position,i)=>({card:pool[i],reversed:reversals.checked&&rnd()<.34,position}));revealed=new Set();renderSpread();drawBtn.textContent="Mescola ancora";oracleText.textContent="Una alla volta. Non correre davanti alle carte."}
function resetTable(clearQuestion=true){drawn=[];revealed=new Set();deckStage.classList.remove("hidden");spreadArea.classList.add("hidden");spreadArea.innerHTML="";revealNote.classList.add("hidden");result.classList.add("hidden");result.innerHTML="";drawBtn.textContent="Inizia la lettura";oracleText.textContent="Fammi una domanda chiara. Al resto penso io.";if(clearQuestion)q.value=""}
function mark(c){if(c.arcana==="Maggiore")return"✦";if(c.suit==="Bastoni")return"│";if(c.suit==="Coppe")return"◡";if(c.suit==="Spade")return"†";return"◇"}
function renderSpread(){deckStage.classList.add("hidden");spreadArea.className="spread-area "+currentSpread;spreadArea.innerHTML="";revealNote.classList.remove("hidden");result.classList.add("hidden");drawn.forEach((d,i)=>{const slot=document.createElement("div");slot.className="card-slot";slot.innerHTML=`<span class="position-label">${d.position.label}</span><button class="tarot-card" type="button" aria-label="Rivela ${d.position.label}"><span class="card-inner"><span class="card-back"><b>✦</b><i>☾</i><small>MORRIS</small></span><span class="card-front ${d.reversed?"reversed":""}"><em>${d.card.arcana}</em><b class="mark">${mark(d.card)}</b><strong>${d.card.name}</strong><small>${d.reversed?"Rovesciata":"Dritta"}</small></span></span></button>`;const btn=slot.querySelector("button");btn.addEventListener("click",()=>{if(revealed.has(i))return;revealed.add(i);btn.classList.add("revealed");if(revealed.size===drawn.length){oracleText.textContent="Bene. Adesso guardiamo il disegno completo.";revealNote.classList.add("hidden");setTimeout(renderResult,500)}});spreadArea.appendChild(slot)})}
function meaning(d){return d.reversed?d.card.reversed:d.card.upright}
function topic(s){s=s.toLowerCase();if(/amor|relaz|coppia|sentiment|ex\b/.test(s))return"relazioni";if(/lavor|carriera|client|profession|azienda/.test(s))return"lavoro";if(/sold|denar|econom|finanz/.test(s))return"risorse";if(/famigli|figli|casa|genitor/.test(s))return"famiglia";return"quadro generale"}
function synthesis(){const majors=drawn.filter(x=>x.card.arcana==="Maggiore").length,rev=drawn.filter(x=>x.reversed).length,courts=drawn.filter(x=>["Fante","Cavaliere","Regina","Re"].includes(x.card.rank||"")).length,suits={Bastoni:0,Coppe:0,Spade:0,Denari:0};drawn.forEach(x=>{if(x.card.suit)suits[x.card.suit]++});const dominant=Object.entries(suits).sort((a,b)=>b[1]-a[1])[0],notes=[];if(majors>=Math.max(2,Math.ceil(drawn.length/3)))notes.push("Gli Arcani Maggiori sono numerosi: qui pesano soprattutto scelte di fondo e passaggi strutturali.");if(rev>=Math.ceil(drawn.length/2))notes.push("Molte carte sono rovesciate: molta energia è interna, trattenuta o in revisione, non semplicemente negativa.");if(courts>=2)notes.push("Le figure di corte ricorrono: persone, ruoli o modi di comportarsi incidono molto sul quadro.");if(dominant[1]>=2){const v={Bastoni:"azione e iniziativa",Coppe:"emozioni e legami",Spade:"pensiero e decisioni",Denari:"realtà pratica e risorse"};notes.push("Dominano "+dominant[0]+": la lettura insiste su "+v[dominant[0]]+".")}for(let i=0;i<drawn.length-1;i++){const a=drawn[i].card.element,b=drawn[i+1].card.element,sup=(a==="Fuoco"&&b==="Aria")||(a==="Aria"&&b==="Fuoco")||(a==="Acqua"&&b==="Terra")||(a==="Terra"&&b==="Acqua"),fr=(a==="Fuoco"&&b==="Acqua")||(a==="Acqua"&&b==="Fuoco")||(a==="Aria"&&b==="Terra")||(a==="Terra"&&b==="Aria");if(sup){notes.push("“"+drawn[i].card.name+"” e “"+drawn[i+1].card.name+"” si sostengono sul piano elementale.");break}if(fr){notes.push("“"+drawn[i].card.name+"” e “"+drawn[i+1].card.name+"” creano attrito elementale: serve mediazione.");break}}return notes}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function renderResult(){const notes=synthesis(),question=q.value.trim();result.classList.remove("hidden");result.innerHTML=`<div class="result-head"><div><span>Lettura di Morris</span><h3>${question?"“"+esc(question)+"”":"Il quadro che emerge"}</h3></div><p>Ambito rilevato: <strong>${topic(question)}</strong></p></div><div class="reading">${drawn.map(d=>`<article><span>${d.position.label}</span><h4>${d.card.name} <small>${d.reversed?"rovesciata":"dritta"}</small></h4><p><strong>In questa posizione:</strong> ${d.position.focus}. La carta porta ${meaning(d)}.</p></article>`).join("")}</div><div class="synthesis"><img src="https://d2ol7oe51mr4n9.cloudfront.net/user_3I2R8XV0b9op50LbwH2h8azHhrT/f70cb9d7-d3ae-4161-b7ea-a7c2bab8c6b2.jpg" alt=""><div><span>Morris mette insieme le carte</span>${(notes.length?notes:["La stesa è equilibrata: nessun seme o gruppo domina nettamente, quindi conta soprattutto la sequenza delle singole posizioni."]).map(n=>"<p>"+n+"</p>").join("")}<p class="final">Il punto non è indovinare un futuro fisso. È vedere quale dinamica stai alimentando adesso e dove può portarti.</p></div></div><button class="reset" id="resetBtn">Nuova domanda</button>`;document.querySelector("#resetBtn").addEventListener("click",()=>{resetTable(true);document.querySelector("#lettura").scrollIntoView({behavior:"smooth"})});result.scrollIntoView({behavior:"smooth",block:"start"})}
