import "./styles.css";
import * as ort from "onnxruntime-web";
import {DemucsProcessor, CONSTANTS} from "demucs-web";

const $=s=>document.querySelector(s);
const fmt=s=>{s=Math.max(0,s||0);return Math.floor(s/60)+":"+String(Math.floor(s%60)).padStart(2,"0")};
const state={ctx:null,original:null,sourceFile:null,tracks:[],nodes:[],playing:false,startedAt:0,offset:0,duration:0,master:1,bpm:100,key:"C",chords:[],autoKeys:false,keyStyle:"PAD",keyIntensity:.45,keyComplexity:.45,humanize:.12,timer:null,keysTimer:null};

document.querySelector("#app").innerHTML=`
<div class="wrap">
<section class="hero"><div class="logo">MORRIS <b>STEM LAB</b></div><div class="sub">Separa. Suona. Remix.</div><div class="privacy">🔒 Il brano resta sul tuo dispositivo</div></section>
<section class="card" id="loader"><div class="drop" id="drop"><h2>Carica un brano</h2><p class="small">MP3, WAV, M4A. Sul PC useremo WebGPU quando disponibile.</p><button class="btn primary">CARICA BRANO</button><input id="file" type="file" accept="audio/*" hidden></div>
<div id="prep" class="hidden" style="margin-top:16px"><div class="row"><strong id="filename"></strong><span class="spacer"></span><span class="status" id="engine"></span></div><div class="progress"><div class="bar" id="bar"></div></div><p class="status" id="status">Pronto.</p><div class="row"><button class="btn primary" id="separate">SEPARA 4 STEM</button><button class="btn dark" id="analyze">ANALIZZA BPM + ACCORDI</button></div></div></section>
<section id="studio" class="hidden">
<div class="transport"><button class="btn primary" id="play">▶ PLAY</button><span class="time" id="time">0:00 / 0:00</span><input class="seek" id="seek" type="range" min="0" max="1000" value="0"><label class="small">MASTER <input id="master" type="range" min="0" max="1.3" step=".01" value="1"></label></div>
<div class="row"><button class="btn dark" id="addTrack">+ AGGIUNGI TRACCIA</button><button class="btn dark" id="record">● REGISTRA</button><input id="addFile" type="file" accept="audio/*" hidden><span class="spacer"></span><button class="btn dark" id="save">SALVA PROGETTO</button><button class="btn primary" id="export">ESPORTA WAV</button></div>
<div class="tracks" id="tracks"></div>
<div class="grid2">
<div class="card"><div class="row"><h2>AUTO KEYS</h2><span class="spacer"></span><button class="chip" id="keysOn">OFF</button></div>
<div class="row"><label class="small">BPM <input id="bpm" type="number" min="40" max="220" value="100"></label><label class="small">STILE <select class="select" id="style"><option>PAD</option><option>PIANO</option><option>RHODES</option><option>HAMMOND</option><option>SYNTH</option><option>ARPEGGIO</option></select></label></div>
<div class="ctrl"><label>INTENSITÀ</label><input id="intensity" type="range" min="0" max="1" step=".01" value=".45"></div><div class="ctrl"><label>COMPLESSITÀ</label><input id="complexity" type="range" min="0" max="1" step=".01" value=".45"></div><div class="ctrl"><label>HUMANIZE</label><input id="humanize" type="range" min="0" max=".3" step=".01" value=".12"></div></div>
<div class="card"><h2>ACCORDI</h2><p class="small">Rilevamento locale beta. Tocca e correggi qualsiasi accordo.</p><div class="chords" id="chords"></div></div>
</div></section></div>`;

function ensureCtx(){if(!state.ctx)state.ctx=new (window.AudioContext||window.webkitAudioContext)({sampleRate:44100});return state.ctx}
async function decodeFile(file){const ctx=ensureCtx();return await ctx.decodeAudioData(await file.arrayBuffer())}
function setStatus(t,p){$("#status").textContent=t;if(p!=null)$("#bar").style.width=Math.round(p*100)+"%"}
async function detectEngine(){let backend="CPU/WASM";if("gpu" in navigator){try{const a=await navigator.gpu.requestAdapter();if(a)backend="WebGPU"}catch{}}$("#engine").textContent="Motore: "+backend;return backend}
$("#drop").onclick=()=>$("#file").click();$("#file").onchange=e=>loadSource(e.target.files[0]);
$("#drop").ondragover=e=>{e.preventDefault()};$("#drop").ondrop=e=>{e.preventDefault();loadSource(e.dataTransfer.files[0])};
async function loadSource(file){if(!file)return;state.sourceFile=file;$("#prep").classList.remove("hidden");$("#filename").textContent=file.name;setStatus("Decodifica audio...",.03);state.original=await decodeFile(file);state.duration=state.original.duration;state.tracks=[makeTrack("ORIGINALE",state.original,"source")];renderTracks();$("#studio").classList.remove("hidden");await detectEngine();setStatus("Brano pronto. Puoi separare oppure già analizzare armonia e tempo.",0);updateTime()}

function makeTrack(name,buffer,type="audio"){return {id:crypto.randomUUID(),name,buffer,type,vol:1,pan:0,mute:false,solo:false,low:0,mid:0,high:0,delay:0,reverb:0,flanger:0,offset:0}}
function renderTracks(){const box=$("#tracks");box.innerHTML="";state.tracks.forEach((t,i)=>{const el=document.createElement("div");el.className="track";el.innerHTML=`<div><h3>${t.name}</h3><div class="tag">${t.type.toUpperCase()}</div><div class="switches"><button class="chip ${t.mute?"on":""}" data-a="mute">M</button><button class="chip ${t.solo?"on":""}" data-a="solo">S</button></div></div><div class="controls">
${ctrl("VOL","vol",t.vol,0,1.25,.01)}${ctrl("PAN","pan",t.pan,-1,1,.01)}${ctrl("LOW","low",t.low,-12,12,.5)}${ctrl("MID","mid",t.mid,-12,12,.5)}${ctrl("HIGH","high",t.high,-12,12,.5)}${ctrl("DELAY","delay",t.delay,0,.8,.01)}${ctrl("REVERB","reverb",t.reverb,0,.8,.01)}${ctrl("FLANGER","flanger",t.flanger,0,.8,.01)}${t.type==="import"?ctrl("OFFSET s","offset",t.offset,0,Math.max(1,state.duration),.1):""}</div>`;el.querySelectorAll("input").forEach(inp=>inp.oninput=()=>{t[inp.dataset.k]=+inp.value;if(state.playing)restartPlayback()});el.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{t[b.dataset.a]=!t[b.dataset.a];renderTracks();if(state.playing)restartPlayback()});box.appendChild(el)})}
function ctrl(l,k,v,min,max,step){return `<div class="ctrl"><label>${l}</label><input data-k="${k}" type="range" min="${min}" max="${max}" step="${step}" value="${v}"></div>`}

$("#separate").onclick=async()=>{if(!state.original)return;$("#separate").disabled=true;try{setStatus("Carico il modello Demucs (la prima volta ~172 MB)...",.05);ort.env.wasm.numThreads=Math.max(1,Math.min(8,navigator.hardwareConcurrency||4));const backend=await detectEngine();const processor=new DemucsProcessor({ort,onProgress:info=>setStatus(`Separazione: segmento ${info.currentSegment}/${info.totalSegments}`,.15+info.progress*.8),onDownloadProgress:(l,t)=>setStatus(`Download modello: ${Math.round(l/t*100)}%`,.05+(l/t)*.1)});if(backend==="WebGPU"){try{ort.env.webgpu={powerPreference:"high-performance"}}catch{}}await processor.loadModel(CONSTANTS.DEFAULT_MODEL_URL);const stereo=toStereo(state.original);setStatus("Separazione AI in corso...",.16);const out=await processor.separate(stereo.left,stereo.right);const ctx=ensureCtx();state.tracks=[["VOCALS",out.vocals],["DRUMS",out.drums],["BASS",out.bass],["OTHER",out.other]].map(([n,s])=>makeTrack(n,fromStereo(ctx,s.left,s.right),"stem"));renderTracks();setStatus("4 stem pronti. Tutto resta locale.",1)}catch(e){console.error(e);setStatus("Separazione non riuscita: "+(e?.message||e),0)}finally{$("#separate").disabled=false}};
function toStereo(b){const n=b.length,l=new Float32Array(n),r=new Float32Array(n);l.set(b.getChannelData(0));r.set(b.numberOfChannels>1?b.getChannelData(1):b.getChannelData(0));return {left:l,right:r}}
function fromStereo(ctx,l,r){const b=ctx.createBuffer(2,l.length,44100);b.copyToChannel(l,0);b.copyToChannel(r,1);return b}

function impulse(ctx,sec=2){const len=ctx.sampleRate*sec,b=ctx.createBuffer(2,len,ctx.sampleRate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,2.5)}return b}
function effectiveMute(t){const anySolo=state.tracks.some(x=>x.solo);return t.mute||(anySolo&&!t.solo)}
function buildChain(ctx,t,dest){const src=ctx.createBufferSource();src.buffer=t.buffer;const g=ctx.createGain();g.gain.value=effectiveMute(t)?0:t.vol;const pan=ctx.createStereoPanner();pan.pan.value=t.pan;const lo=ctx.createBiquadFilter();lo.type="lowshelf";lo.frequency.value=180;lo.gain.value=t.low;const mid=ctx.createBiquadFilter();mid.type="peaking";mid.frequency.value=1200;mid.Q.value=.8;mid.gain.value=t.mid;const hi=ctx.createBiquadFilter();hi.type="highshelf";hi.frequency.value=5000;hi.gain.value=t.high;src.connect(lo).connect(mid).connect(hi).connect(pan).connect(g).connect(dest);
if(t.delay>0){const d=ctx.createDelay(1),fb=ctx.createGain(),wet=ctx.createGain();d.delayTime.value=.28;fb.gain.value=.24;wet.gain.value=t.delay;hi.connect(d);d.connect(fb).connect(d);d.connect(wet).connect(dest)}
if(t.reverb>0){const cv=ctx.createConvolver(),wet=ctx.createGain();cv.buffer=impulse(ctx,1.8);wet.gain.value=t.reverb;hi.connect(cv).connect(wet).connect(dest)}
if(t.flanger>0){const dl=ctx.createDelay(.05),wet=ctx.createGain(),osc=ctx.createOscillator(),og=ctx.createGain();dl.delayTime.value=.006;og.gain.value=.003;osc.frequency.value=.25+.7*t.flanger;wet.gain.value=t.flanger*.65;osc.connect(og).connect(dl.delayTime);hi.connect(dl).connect(wet).connect(dest);osc.start();return {src,osc}}return {src}}
function stopNodes(){state.nodes.forEach(n=>{try{n.src?.stop()}catch{}try{n.osc?.stop()}catch{}});state.nodes=[]}
function playAt(offset){const ctx=ensureCtx();stopNodes();const master=ctx.createGain();master.gain.value=state.master;master.connect(ctx.destination);state.tracks.forEach(t=>{const n=buildChain(ctx,t,master);const local=Math.max(0,offset-t.offset);if(local<t.buffer.duration){n.src.start(ctx.currentTime,local);state.nodes.push(n)}});state.startedAt=ctx.currentTime-offset;state.offset=offset;state.playing=true;$("#play").textContent="❚❚ PAUSA";startClock();startKeys()}
function pause(){if(!state.playing)return;state.offset=Math.min(state.duration,ensureCtx().currentTime-state.startedAt);state.playing=false;stopNodes();stopKeys();$("#play").textContent="▶ PLAY";updateTime()}
function restartPlayback(){if(state.playing){const o=ensureCtx().currentTime-state.startedAt;playAt(o)}}
$("#play").onclick=async()=>{await ensureCtx().resume();state.playing?pause():playAt(state.offset>=state.duration?0:state.offset)};
function startClock(){clearInterval(state.timer);state.timer=setInterval(()=>{if(!state.playing)return;state.offset=ensureCtx().currentTime-state.startedAt;if(state.offset>=state.duration){pause();state.offset=0}updateTime()},100)}
function updateTime(){const o=state.playing?Math.min(state.duration,ensureCtx().currentTime-state.startedAt):state.offset;$("#time").textContent=fmt(o)+" / "+fmt(state.duration);$("#seek").value=state.duration?Math.round(o/state.duration*1000):0}
$("#seek").oninput=e=>{const o=(+e.target.value/1000)*state.duration;state.offset=o;if(state.playing)playAt(o);else updateTime()}
$("#master").oninput=e=>state.master=+e.target.value;

$("#addTrack").onclick=()=>$("#addFile").click();$("#addFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;const b=await decodeFile(f);state.tracks.push(makeTrack(f.name,b,"import"));state.duration=Math.max(state.duration,b.duration);renderTracks()};
let rec=null,chunks=[];$("#record").onclick=async()=>{if(!rec){const stream=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(stream);chunks=[];rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=async()=>{const b=await decodeFile(new File([new Blob(chunks)],"Registrazione.webm"));state.tracks.push(makeTrack("REGISTRAZIONE",b,"import"));renderTracks();stream.getTracks().forEach(t=>t.stop());rec=null;$("#record").textContent="● REGISTRA"};rec.start();$("#record").textContent="■ STOP"}else rec.stop()};

$("#analyze").onclick=async()=>{if(!state.original)return;setStatus("Analisi locale di tempo e armonia...",.2);const b=state.original;state.bpm=estimateBpm(b);$("#bpm").value=state.bpm;state.chords=detectChords(b,state.bpm);renderChords();setStatus(`Analisi pronta: ~${state.bpm} BPM, accordi beta modificabili.`,1)};
function monoSamples(b,rate=4000){const step=Math.max(1,Math.floor(b.sampleRate/rate)),src=b.getChannelData(0),out=new Float32Array(Math.floor(src.length/step));for(let i=0,j=0;i<src.length&&j<out.length;i+=step,j++)out[j]=src[i];return {data:out,rate:b.sampleRate/step}}
function estimateBpm(b){const {data,rate}=monoSamples(b,1000),win=Math.max(20,Math.floor(rate*.05)),env=[];for(let i=0;i+win<data.length;i+=win){let s=0;for(let j=0;j<win;j++)s+=data[i+j]*data[i+j];env.push(Math.sqrt(s/win))}let diff=env.map((x,i)=>Math.max(0,x-(env[i-1]||x)));let best=100,score=-1;for(let bpm=60;bpm<=180;bpm++){const lag=Math.round((60/bpm)/.05);let s=0;for(let i=lag;i<diff.length;i++)s+=diff[i]*diff[i-lag];if(s>score){score=s;best=bpm}}return best}
const NAMES=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
function goertzel(samples,sr,f){const w=2*Math.PI*f/sr,c=2*Math.cos(w);let s0=0,s1=0,s2=0;for(let i=0;i<samples.length;i++){s0=samples[i]+c*s1-s2;s2=s1;s1=s0}return s1*s1+s2*s2-c*s1*s2}
function detectChords(b,bpm){const beat=60/bpm,seg=beat*4,src=b.getChannelData(0),sr=b.sampleRate,out=[];for(let t=0;t<b.duration;t+=seg){const start=Math.floor(t*sr),end=Math.min(src.length,start+Math.floor(Math.min(seg,2)*sr)),step=4,arr=new Float32Array(Math.floor((end-start)/step));for(let i=start,j=0;i<end;i+=step,j++)arr[j]=src[i];const rr=sr/step,chroma=NAMES.map((_,pc)=>{let s=0;for(let oct=3;oct<=5;oct++){const midi=12*(oct+1)+pc,f=440*Math.pow(2,(midi-69)/12);s+=goertzel(arr,rr,f)}return s});let best={score:-1,name:"C"};for(let r=0;r<12;r++){const maj=chroma[r]+.85*chroma[(r+4)%12]+.8*chroma[(r+7)%12],min=chroma[r]+.85*chroma[(r+3)%12]+.8*chroma[(r+7)%12];if(maj>best.score)best={score:maj,name:NAMES[r]};if(min>best.score)best={score:min,name:NAMES[r]+"m"}}out.push({t,name:best.name})}return out}
function renderChords(){const c=$("#chords");c.innerHTML="";state.chords.forEach((x,i)=>{const d=document.createElement("div");d.className="chord";d.innerHTML=`<div class="small">${fmt(x.t)}</div><input value="${x.name}">`;d.querySelector("input").onchange=e=>x.name=e.target.value.trim();c.appendChild(d)})}
$("#bpm").onchange=e=>state.bpm=+e.target.value;$("#style").onchange=e=>state.keyStyle=e.target.value;$("#intensity").oninput=e=>state.keyIntensity=+e.target.value;$("#complexity").oninput=e=>state.keyComplexity=+e.target.value;$("#humanize").oninput=e=>state.humanize=+e.target.value;$("#keysOn").onclick=()=>{state.autoKeys=!state.autoKeys;$("#keysOn").textContent=state.autoKeys?"ON":"OFF";$("#keysOn").classList.toggle("on",state.autoKeys);if(state.playing){stopKeys();startKeys()}};
let keyVoices=[];function chordNotes(name){const m=name.match(/^([A-G])(#|b)?(m)?/);if(!m)return [60,64,67];const map={C:0,D:2,E:4,F:5,G:7,A:9,B:11};let r=map[m[1]]+(m[2]==="#"?1:m[2]==="b"?-1:0);return [60+r,60+r+(m[3]?3:4),67+r]}
function startKeys(){stopKeys();if(!state.autoKeys||!state.chords.length)return;const ctx=ensureCtx();let last=-1;state.keysTimer=setInterval(()=>{if(!state.playing)return;const pos=ctx.currentTime-state.startedAt,idx=Math.max(0,state.chords.findLastIndex(c=>c.t<=pos));if(idx===last)return;last=idx;const ch=state.chords[idx],dur=Math.min(4*60/state.bpm,(state.chords[idx+1]?.t??state.duration)-pos);playChord(ctx,chordNotes(ch.name),Math.max(.15,dur))},80)}
function playChord(ctx,notes,dur){const now=ctx.currentTime,g=ctx.createGain();g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.09*state.keyIntensity,now+.03);g.gain.exponentialRampToValueAtTime(.0001,now+dur);g.connect(ctx.destination);notes.forEach((n,i)=>{const o=ctx.createOscillator();o.type=state.keyStyle==="SYNTH"?"sawtooth":state.keyStyle==="HAMMOND"?"square":"sine";o.frequency.value=440*Math.pow(2,(n-69)/12);o.connect(g);o.start(now+i*state.humanize*.02);o.stop(now+dur+.05);keyVoices.push(o)})}
function stopKeys(){clearInterval(state.keysTimer);state.keysTimer=null;keyVoices.forEach(o=>{try{o.stop()}catch{}});keyVoices=[]}

$("#save").onclick=()=>{const p={name:state.sourceFile?.name||"Progetto",bpm:state.bpm,chords:state.chords,autoKeys:state.autoKeys,keyStyle:state.keyStyle,keyIntensity:state.keyIntensity,keyComplexity:state.keyComplexity,humanize:state.humanize,tracks:state.tracks.map(t=>({name:t.name,type:t.type,vol:t.vol,pan:t.pan,mute:t.mute,solo:t.solo,low:t.low,mid:t.mid,high:t.high,delay:t.delay,reverb:t.reverb,flanger:t.flanger,offset:t.offset}))};localStorage.setItem("morrisStemLab:lastProject",JSON.stringify(p));alert("Impostazioni progetto salvate su questo dispositivo.")};

$("#export").onclick=async()=>{if(!state.tracks.length)return;$("#export").disabled=true;$("#export").textContent="RENDER...";try{const sr=44100,len=Math.ceil(state.duration*sr),off=new OfflineAudioContext(2,len,sr),master=off.createGain();master.gain.value=state.master;master.connect(off.destination);state.tracks.forEach(t=>{const n=buildChain(off,t,master);n.src.start(Math.max(0,t.offset),0)});if(state.autoKeys&&state.chords.length)scheduleOfflineKeys(off,master);const b=await off.startRendering();downloadBlob(new Blob([wavBytes(b)],{type:"audio/wav"}),(state.sourceFile?.name?.replace(/\.[^.]+$/,"")||"Morris_Remix")+"_REMIX.wav")}catch(e){alert("Export non riuscito: "+e.message)}finally{$("#export").disabled=false;$("#export").textContent="ESPORTA WAV"}};
function scheduleOfflineKeys(ctx,dest){state.chords.forEach((ch,i)=>{const t=ch.t,dur=Math.max(.15,(state.chords[i+1]?.t??state.duration)-t),g=ctx.createGain();g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.08*state.keyIntensity,t+.03);g.gain.exponentialRampToValueAtTime(.0001,Math.max(t+.05,t+dur-.02));g.connect(dest);chordNotes(ch.name).forEach(n=>{const o=ctx.createOscillator();o.type=state.keyStyle==="SYNTH"?"sawtooth":"sine";o.frequency.value=440*Math.pow(2,(n-69)/12);o.connect(g);o.start(t);o.stop(t+dur)})})}
function wavBytes(b){const ch=b.numberOfChannels,sr=b.sampleRate,n=b.length,buf=new ArrayBuffer(44+n*ch*2),v=new DataView(buf),w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,"RIFF");v.setUint32(4,36+n*ch*2,true);w(8,"WAVEfmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,sr,true);v.setUint32(28,sr*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);w(36,"data");v.setUint32(40,n*ch*2,true);let o=44;for(let i=0;i<n;i++)for(let c=0;c<ch;c++){let s=Math.max(-1,Math.min(1,b.getChannelData(c)[i]));v.setInt16(o,s<0?s*32768:s*32767,true);o+=2}return buf}
function downloadBlob(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}
